// flow-typed signature: 83d06c2b7d17c8034d736dd55b433bef
// flow-typed version: <<STUB>>/apollo-upload-client_v^14.1.3/flow_v0.133.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-upload-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-upload-client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-upload-client/public/createUploadLink' {
  declare module.exports: any;
}

declare module 'apollo-upload-client/public/formDataAppendFile' {
  declare module.exports: any;
}

declare module 'apollo-upload-client/public' {
  declare module.exports: any;
}

declare module 'apollo-upload-client/public/isExtractableFile' {
  declare module.exports: any;
}

declare module 'apollo-upload-client/public/ReactNativeFile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-upload-client/public/createUploadLink.js' {
  declare module.exports: $Exports<'apollo-upload-client/public/createUploadLink'>;
}
declare module 'apollo-upload-client/public/formDataAppendFile.js' {
  declare module.exports: $Exports<'apollo-upload-client/public/formDataAppendFile'>;
}
declare module 'apollo-upload-client/public/index' {
  declare module.exports: $Exports<'apollo-upload-client/public'>;
}
declare module 'apollo-upload-client/public/index.js' {
  declare module.exports: $Exports<'apollo-upload-client/public'>;
}
declare module 'apollo-upload-client/public/isExtractableFile.js' {
  declare module.exports: $Exports<'apollo-upload-client/public/isExtractableFile'>;
}
declare module 'apollo-upload-client/public/ReactNativeFile.js' {
  declare module.exports: $Exports<'apollo-upload-client/public/ReactNativeFile'>;
}
