// flow-typed signature: 6a8314af7a8eda830d25acc4bf016079
// flow-typed version: <<STUB>>/@oryd/kratos-client_v^0.4.6-alpha.1/flow_v0.133.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@oryd/kratos-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@oryd/kratos-client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@oryd/kratos-client/dist/api' {
  declare module.exports: any;
}

declare module '@oryd/kratos-client/dist/api/adminApi' {
  declare module.exports: any;
}

declare module '@oryd/kratos-client/dist/api/apis' {
  declare module.exports: any;
}

declare module '@oryd/kratos-client/dist/api/commonApi' {
  declare module.exports: any;
}

declare module '@oryd/kratos-client/dist/api/healthApi' {
  declare module.exports: any;
}

declare module '@oryd/kratos-client/dist/api/publicApi' {
  declare module.exports: any;
}

declare module '@oryd/kratos-client/dist/api/versionApi' {
  declare module.exports: any;
}

declare module '@oryd/kratos-client/dist/model/completeSelfServiceBrowserProfileManagementFlowPayload' {
  declare module.exports: any;
}

declare module '@oryd/kratos-client/dist/model/completeSelfServiceBrowserSettingsStrategyProfileFlowPayload' {
  declare module.exports: any;
}

declare module '@oryd/kratos-client/dist/model/errorContainer' {
  declare module.exports: any;
}

declare module '@oryd/kratos-client/dist/model/form' {
  declare module.exports: any;
}

declare module '@oryd/kratos-client/dist/model/formField' {
  declare module.exports: any;
}

declare module '@oryd/kratos-client/dist/model/genericError' {
  declare module.exports: any;
}

declare module '@oryd/kratos-client/dist/model/genericErrorPayload' {
  declare module.exports: any;
}

declare module '@oryd/kratos-client/dist/model/healthNotReadyStatus' {
  declare module.exports: any;
}

declare module '@oryd/kratos-client/dist/model/healthStatus' {
  declare module.exports: any;
}

declare module '@oryd/kratos-client/dist/model/identity' {
  declare module.exports: any;
}

declare module '@oryd/kratos-client/dist/model/loginRequest' {
  declare module.exports: any;
}

declare module '@oryd/kratos-client/dist/model/loginRequestMethod' {
  declare module.exports: any;
}

declare module '@oryd/kratos-client/dist/model/loginRequestMethodConfig' {
  declare module.exports: any;
}

declare module '@oryd/kratos-client/dist/model/message' {
  declare module.exports: any;
}

declare module '@oryd/kratos-client/dist/model/modelError' {
  declare module.exports: any;
}

declare module '@oryd/kratos-client/dist/model/models' {
  declare module.exports: any;
}

declare module '@oryd/kratos-client/dist/model/oidcStrategyCredentialsConfig' {
  declare module.exports: any;
}

declare module '@oryd/kratos-client/dist/model/oidcStrategyRequestMethod' {
  declare module.exports: any;
}

declare module '@oryd/kratos-client/dist/model/profileManagementRequest' {
  declare module.exports: any;
}

declare module '@oryd/kratos-client/dist/model/providerCredentialsConfig' {
  declare module.exports: any;
}

declare module '@oryd/kratos-client/dist/model/recoveryAddress' {
  declare module.exports: any;
}

declare module '@oryd/kratos-client/dist/model/recoveryRequest' {
  declare module.exports: any;
}

declare module '@oryd/kratos-client/dist/model/recoveryRequestMethod' {
  declare module.exports: any;
}

declare module '@oryd/kratos-client/dist/model/registrationRequest' {
  declare module.exports: any;
}

declare module '@oryd/kratos-client/dist/model/registrationRequestMethod' {
  declare module.exports: any;
}

declare module '@oryd/kratos-client/dist/model/registrationRequestMethodConfig' {
  declare module.exports: any;
}

declare module '@oryd/kratos-client/dist/model/requestMethodConfig' {
  declare module.exports: any;
}

declare module '@oryd/kratos-client/dist/model/session' {
  declare module.exports: any;
}

declare module '@oryd/kratos-client/dist/model/settingsRequest' {
  declare module.exports: any;
}

declare module '@oryd/kratos-client/dist/model/settingsRequestMethod' {
  declare module.exports: any;
}

declare module '@oryd/kratos-client/dist/model/verifiableAddress' {
  declare module.exports: any;
}

declare module '@oryd/kratos-client/dist/model/verificationRequest' {
  declare module.exports: any;
}

declare module '@oryd/kratos-client/dist/model/version' {
  declare module.exports: any;
}

// Filename aliases
declare module '@oryd/kratos-client/dist/api.js' {
  declare module.exports: $Exports<'@oryd/kratos-client/dist/api'>;
}
declare module '@oryd/kratos-client/dist/api/adminApi.js' {
  declare module.exports: $Exports<'@oryd/kratos-client/dist/api/adminApi'>;
}
declare module '@oryd/kratos-client/dist/api/apis.js' {
  declare module.exports: $Exports<'@oryd/kratos-client/dist/api/apis'>;
}
declare module '@oryd/kratos-client/dist/api/commonApi.js' {
  declare module.exports: $Exports<'@oryd/kratos-client/dist/api/commonApi'>;
}
declare module '@oryd/kratos-client/dist/api/healthApi.js' {
  declare module.exports: $Exports<'@oryd/kratos-client/dist/api/healthApi'>;
}
declare module '@oryd/kratos-client/dist/api/publicApi.js' {
  declare module.exports: $Exports<'@oryd/kratos-client/dist/api/publicApi'>;
}
declare module '@oryd/kratos-client/dist/api/versionApi.js' {
  declare module.exports: $Exports<'@oryd/kratos-client/dist/api/versionApi'>;
}
declare module '@oryd/kratos-client/dist/model/completeSelfServiceBrowserProfileManagementFlowPayload.js' {
  declare module.exports: $Exports<'@oryd/kratos-client/dist/model/completeSelfServiceBrowserProfileManagementFlowPayload'>;
}
declare module '@oryd/kratos-client/dist/model/completeSelfServiceBrowserSettingsStrategyProfileFlowPayload.js' {
  declare module.exports: $Exports<'@oryd/kratos-client/dist/model/completeSelfServiceBrowserSettingsStrategyProfileFlowPayload'>;
}
declare module '@oryd/kratos-client/dist/model/errorContainer.js' {
  declare module.exports: $Exports<'@oryd/kratos-client/dist/model/errorContainer'>;
}
declare module '@oryd/kratos-client/dist/model/form.js' {
  declare module.exports: $Exports<'@oryd/kratos-client/dist/model/form'>;
}
declare module '@oryd/kratos-client/dist/model/formField.js' {
  declare module.exports: $Exports<'@oryd/kratos-client/dist/model/formField'>;
}
declare module '@oryd/kratos-client/dist/model/genericError.js' {
  declare module.exports: $Exports<'@oryd/kratos-client/dist/model/genericError'>;
}
declare module '@oryd/kratos-client/dist/model/genericErrorPayload.js' {
  declare module.exports: $Exports<'@oryd/kratos-client/dist/model/genericErrorPayload'>;
}
declare module '@oryd/kratos-client/dist/model/healthNotReadyStatus.js' {
  declare module.exports: $Exports<'@oryd/kratos-client/dist/model/healthNotReadyStatus'>;
}
declare module '@oryd/kratos-client/dist/model/healthStatus.js' {
  declare module.exports: $Exports<'@oryd/kratos-client/dist/model/healthStatus'>;
}
declare module '@oryd/kratos-client/dist/model/identity.js' {
  declare module.exports: $Exports<'@oryd/kratos-client/dist/model/identity'>;
}
declare module '@oryd/kratos-client/dist/model/loginRequest.js' {
  declare module.exports: $Exports<'@oryd/kratos-client/dist/model/loginRequest'>;
}
declare module '@oryd/kratos-client/dist/model/loginRequestMethod.js' {
  declare module.exports: $Exports<'@oryd/kratos-client/dist/model/loginRequestMethod'>;
}
declare module '@oryd/kratos-client/dist/model/loginRequestMethodConfig.js' {
  declare module.exports: $Exports<'@oryd/kratos-client/dist/model/loginRequestMethodConfig'>;
}
declare module '@oryd/kratos-client/dist/model/message.js' {
  declare module.exports: $Exports<'@oryd/kratos-client/dist/model/message'>;
}
declare module '@oryd/kratos-client/dist/model/modelError.js' {
  declare module.exports: $Exports<'@oryd/kratos-client/dist/model/modelError'>;
}
declare module '@oryd/kratos-client/dist/model/models.js' {
  declare module.exports: $Exports<'@oryd/kratos-client/dist/model/models'>;
}
declare module '@oryd/kratos-client/dist/model/oidcStrategyCredentialsConfig.js' {
  declare module.exports: $Exports<'@oryd/kratos-client/dist/model/oidcStrategyCredentialsConfig'>;
}
declare module '@oryd/kratos-client/dist/model/oidcStrategyRequestMethod.js' {
  declare module.exports: $Exports<'@oryd/kratos-client/dist/model/oidcStrategyRequestMethod'>;
}
declare module '@oryd/kratos-client/dist/model/profileManagementRequest.js' {
  declare module.exports: $Exports<'@oryd/kratos-client/dist/model/profileManagementRequest'>;
}
declare module '@oryd/kratos-client/dist/model/providerCredentialsConfig.js' {
  declare module.exports: $Exports<'@oryd/kratos-client/dist/model/providerCredentialsConfig'>;
}
declare module '@oryd/kratos-client/dist/model/recoveryAddress.js' {
  declare module.exports: $Exports<'@oryd/kratos-client/dist/model/recoveryAddress'>;
}
declare module '@oryd/kratos-client/dist/model/recoveryRequest.js' {
  declare module.exports: $Exports<'@oryd/kratos-client/dist/model/recoveryRequest'>;
}
declare module '@oryd/kratos-client/dist/model/recoveryRequestMethod.js' {
  declare module.exports: $Exports<'@oryd/kratos-client/dist/model/recoveryRequestMethod'>;
}
declare module '@oryd/kratos-client/dist/model/registrationRequest.js' {
  declare module.exports: $Exports<'@oryd/kratos-client/dist/model/registrationRequest'>;
}
declare module '@oryd/kratos-client/dist/model/registrationRequestMethod.js' {
  declare module.exports: $Exports<'@oryd/kratos-client/dist/model/registrationRequestMethod'>;
}
declare module '@oryd/kratos-client/dist/model/registrationRequestMethodConfig.js' {
  declare module.exports: $Exports<'@oryd/kratos-client/dist/model/registrationRequestMethodConfig'>;
}
declare module '@oryd/kratos-client/dist/model/requestMethodConfig.js' {
  declare module.exports: $Exports<'@oryd/kratos-client/dist/model/requestMethodConfig'>;
}
declare module '@oryd/kratos-client/dist/model/session.js' {
  declare module.exports: $Exports<'@oryd/kratos-client/dist/model/session'>;
}
declare module '@oryd/kratos-client/dist/model/settingsRequest.js' {
  declare module.exports: $Exports<'@oryd/kratos-client/dist/model/settingsRequest'>;
}
declare module '@oryd/kratos-client/dist/model/settingsRequestMethod.js' {
  declare module.exports: $Exports<'@oryd/kratos-client/dist/model/settingsRequestMethod'>;
}
declare module '@oryd/kratos-client/dist/model/verifiableAddress.js' {
  declare module.exports: $Exports<'@oryd/kratos-client/dist/model/verifiableAddress'>;
}
declare module '@oryd/kratos-client/dist/model/verificationRequest.js' {
  declare module.exports: $Exports<'@oryd/kratos-client/dist/model/verificationRequest'>;
}
declare module '@oryd/kratos-client/dist/model/version.js' {
  declare module.exports: $Exports<'@oryd/kratos-client/dist/model/version'>;
}
